#!/bin/bash
#
# This file is part of the 'Simple Sokoban' project.
# It has been contributed by Patrick Monnerat.
#
# MIT LICENSE
#
# Copyright (C) 2014-2023 Mateusz Viste
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

ME=`basename "${0}"`

case "${1}" in
-*|'')	echo "${ME} transforms a data file into C code." 1>&2
	echo 'Copyright (C) Mateusz Viste 2014-2023' 1>&2
	echo "Usage: ${ME} <filename>" 1>&2
	exit 1
	;;
esac

[ -f "${1}" -a -r "${1}" ] || {
	echo "Error: cannot read '${1}'." 1>&2
	exit 3
}

VARNAME=${1/#[^A-Za-z]/_}
VARNAME=${VARNAME//[^0-9A-Za-z]/_}

echo "unsigned char ${VARNAME}[] = {"
(cat "${1}"; echo -n -e '\0') |
	od -An -tx1 -w15 | sed -e 's/ \([^ ][^ ]\)/0x\U\1,/g;s/^/  /;$s/,$//'
echo '};'
echo "size_t ${VARNAME}_len = sizeof(${VARNAME}) - 1;"
exit 0
